export const DEFAULTS = {
  BASE_URL: 'http://127.0.0.1:8080/v1',
  MODEL: 'qwen2.5-coder-7b-instruct',
  TEMPERATURE: 0.1,
  MAX_TOKENS: 8192,
  AGENT_MAX_ITERATIONS: 25,
  TOOL_OUTPUT_TRUNCATE: 2000,
} as const

export const ENV_KEYS = {
  BASE_URL: 'LOCUS_BASE_URL',
  MODEL: 'LOCUS_MODEL',
  TEMPERATURE: 'LOCUS_TEMPERATURE',
  MAX_TOKENS: 'LOCUS_MAX_TOKENS',
  BACKEND: 'LOCUS_BACKEND',
} as const
